version: '2.3'

services:
  darknet-container:
    build:
      context: .
      args:
        arch: " -gencode arch=compute_61,code=[sm_61,compute_61]"
    runtime: nvidia
    image: limwenyao/darknet:dev-arch61
    container_name: darknet-container
    stdin_open: true
    tty: true
    ports:
    - "8888:8888"
    volumes:
      - ./data:/mnt/data
      - ./src:/mnt/src


